@baseUrl = http://localhost:3000

# MESSAGES
### List all messages
GET {{baseUrl}}/messages

### list messages for user with id
GET {{baseUrl}}/messages/1

### Create a new message
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "new message",
  "from": 9,
  "to": 9,
  "read": false,
  "createdAt": "2025-09-20T17:00:00.000Z"
}
### update a message with id
PATCH {{baseUrl}}/messages/2
Content-Type: application/json

{
  "text": "Hello newUser! ",
  "read": true
}

### delete a message with id
DELETE {{baseUrl}}/messages/1


# USERS

### List all users
GET {{baseUrl}}/users

### Get user by id
GET {{baseUrl}}/users/1

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "newuser",
  "email": "user@gmail.com",
    "password": "password123"
}

### update a user with id
PATCH {{baseUrl}}/users/1
Content-Type: application/json
{
  "username": "updateduser",
}
### delete a user with id
DELETE {{baseUrl}}/users/4
